---

- name: Include distribution-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- include_tasks: requirements.yml

# sumo.conf is deprecated in prefence of user.properties
# This should be sym-linked by /opt/SumoCollector/config/user.properties
# in mounted into container
- name: 'Ensure sumologic_config_dir exists'
  file:
    state: directory
    dest: "{{ sumologic_config_dir }}"
    mode: 0700
    owner: "{{ sumologic_config_dir_owner }}"

- name: 'Template SumoCollector files'
  template:
    src: "{{ item }}"
    dest: "{{ sumologic_config_dir }}/{{item}}"
    mode: 0700
    owner: "{{ sumologic_config_dir_owner }}"
  notify: Restart SumoCollector
  with_items:
    - user.properties

- name: 'Download SumoCollector redhat'
  get_url:
    url: '{{ sumocollector_installer_rpm }}'
    dest: '{{ sumologic_installer_rpm_local_folder }}/sumo_collector.rpm'
  when: ansible_os_family == "RedHat"

- name: 'Define initial SumoCollector sources'
  set_fact:
    sumologic_collector_log_paths: "{{ sumologic_collector_default_log_path|list + sumologic_collector_application_log_path|list }}"

- name: 'Create collector configuration'
  template:
    src: collector.json.j2
    dest: /etc/sumologic-collector.json
  notify: Restart SumoCollector
  when: sumologic_single_source_file == "yes"

- name: 'Ensure sumo sources directory exists'
  file:
    state: directory
    dest: "{{ sumologic_sources_dir }}"
  when: sumologic_single_source_file != "yes"

- name: 'Ensure sumo temp data and logs dir exists'
  file:
    state: directory
    dest: "{{ sumologic_host_dir }}"

- name: build collectors
  template:
    src: generic-collector.json.j2
    dest: "/etc/sumo/sumo.d/{{ item.name }}.json"
  with_items: "{{ sumologic_collector_log_paths }}"
  notify: Restart SumoCollector

- name: 'Set udp limits for sumo (native and inherited by container)'
  sysctl:
    name: "{{ item.n }}"
    value: "{{ item.v }}"
    state: present
    sysctl_set: yes
    reload: yes
  with_items:
   - { n: 'net.core.wmem_max', v: 8388608 }
   - { n: 'net.core.rmem_max', v: 8388608 }

- name: 'Install SumoCollector yum'
  yum:
    name: '{{ sumologic_installer_rpm_local_folder }}/sumo_collector.rpm'
    state: present
  when: ansible_os_family == "RedHat"
  notify: Restart SumoCollector
